name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Test failed
        run: exit 1
      - uses: actions/checkout@v3
      - name: test echo
        if: failure()
        run: echo "job failed"
    outputs:
      status: ${{ job.status }}

  Vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      # access preview url
      - run: echo ${{steps.waitForVercel.outputs.url}}
    outputs:
      url: ${{ steps.waitForVercel.outputs.url }}

  Test:
    needs: Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{needs.Vercel.outputs.url}}
